In [ ]:
pip install numpy


In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as n
arr=n.zeros((10,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.full((4,7),9)
print(arr)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [ ]:
import numpy as np
arr=np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr=np.arange(2,100,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [ ]:
import numpy as np
even=np.arange(2,200,2)
print(even)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [ ]:
import numpy as np
arr=np.arange(1,200,2)
print(arr)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199]


In [ ]:
import numpy as np
arr=np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [ ]:
import numpy as np
arr=np.random.rand(10)
print(arr)

[0.73719412 0.83489846 0.72474959 0.0671234  0.77212483 0.79866298
 0.92677254 0.66069831 0.30466881 0.60725307]


In [ ]:
import numpy as np
arr=np.random.randn(10)
print(arr)

[-0.01069327  0.17653649  0.77158571 -0.12571287  1.91095634  0.42883972
 -1.58524782  1.1837503  -0.61691107  1.13786554]


In [ ]:
import numpy as np
arr=np.random.randint(10)
print(arr)

4


In [ ]:
import numpy as np
colours=["red","green","pink","yellow","blue","sky blue","white","black"]
print(np.random.choice(colours,3))

['pink' 'black' 'red']


In [ ]:
import numpy as np
arr=np.array([1,2,3])
new=arr.copy()
new[1]=100
print("array value is :",arr)
print("copy value is:",new)

array value is : [1 2 3]
copy value is: [  1 100   3]


In [ ]:
import numpy as np
arr=np.array([1,2,3])
new=arr.view()
new[1]=100
print("array value is:",arr)
print("view value is:",new)

array value is: [  1 100   3]
view value is: [  1 100   3]


In [ ]:
import numpy as np
arr=np.array([5,10,15,20,25,30,35,40])
arr +=10
print("updated array value is:",arr)

updated array value is: [15 20 25 30 35 40 45 50]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.add(a,b))

[ 7  9 11 13 15]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.subtract(a,b))

[-5 -5 -5 -5 -5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.multiply(a,b))

[ 6 14 24 36 50]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.divide(a,b))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.dot(a,b))

130


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(sum(a))

45


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(a))

5.0


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.std(a))

2.581988897471611


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.min(a))

1


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.max(a))

9


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [ ]:
import numpy as np
a=np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.sort(a))

[  1   3   4   4   7   8   9   9  11  34 141]


In [ ]:
import numpy as np
a=np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.unique(a))

[  1   3   4   7   8   9  11  34 141]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.ndim)
print(a.dtype)


(9,)
9
8
1
int64


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,4,3,2]])
print(a.shape)
print(a.ndim)
print(a[0,1])
print(a[1,1])
print(a[:,1])
print(a[])

(2, 4)
2
2
4
[2 4]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("original array",arr)
new=arr.reshape(5,3)
print(new)

original array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
